dist: bionic
language: bash
services:
- docker
before_install:
- docker build -t m0rf30/arch-arm-crosscompile .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  global:
  - secure: c+JWFz/uPXA/Z4gT2cHxYuLeLUL5bm+OV1Yd/LmQ58hXFdV9OHJFWBX7VfJucnioUuZfWQGsVrEkYt+38oaVEqZGHLQ7qANu56EKYl0bOE/j0rPOebC6RvqMWcnyfd46DnesuULKaF9K0XXF8k2aJxMVdBysue6xN9afVnGNA++JPmYk1V8wutrRHxygDx0/52G0lp8buAh6MNWBHY0aNkBHPEGKuVA4Fpd6gdTtoo7e5kJoXK4IRx5AyQKb/RJwSUNWCgvEmBR+AJdJb9md0StyKkC51IG4YdNjRq6587r27G+4ZtODz7xJ10mtSpTQus8UgcVaO8kRbbaCYUW17KVDfEVzkbon+6u+Ik5E2ujQ3FhGIKh5IGdz5Ul/P6Dal95M2svS06kGdQEqcOeN4M9CP2BYs+M8z/bWbsNyLS8q4YqDdncBNyc5DvP0PAhzjSVghRPzIYY2OkmacbJTVqAdkmFiM+AzbndKZx2Ilvm+4PcEcgfQzvoic+oYs7wAKEakZG46q4Xx7m6Rpwz/Z6kacQ2Rzo+ZJ0RYzoD15MatoS3qkifFoW8/R9QMdvfhPiYrka/9vTl0pDEp8hN7gZHXdRvAXrFrSJTsFf6kFpWteAKr5OyUvcTeVhzx3QRBnIa4jNLoVsYsLaytVTX6BY11gPJIRK+1ZAVnz6UVxeE=
  - secure: gZyFrGiOqiBtpKd7QBCCdmQZal2KoJ30K2ScUA3Q+E5CxojRSSM9cYsojxFrRiWkGIhw5MGG9ig3Msj5RIUvegOfQm7H2T5EYJcq4sBajgTqLTTklXnv8m5G8MyAiJGrbFb5KA1w5s4DnyLkNrkzaPskWhGKdGnoI/w4G532ZbJp1HbusmkKt1IOh0edcfxadKzy6J8l54m2GMEZMlsAgqFIIs4L9KE0zY/rU6DcZWjV/Luouheavt7rQvGAX9XG4r0pV8WzAyK3cndijZMDV2nMgC3UurJA8OXCAIFzwm4oLat98747ewp6lrv87dbKqxhDUvQucCuRYjxFMsKldAahZqiwJKBbnwU54XVCypOpGwTmOphyWXdExKy1ExMdCP+q9/X/uYOEGJhimLQgQmnmqH+X9uJZzYM+/gNdq0BUYaU2AshuavMiwGUI70wl2B4Y5B5WnweVC7INd/legnL96T3g8IBGOSpuPNXzhReZmNlkno2Yfgvy616hW/NIQ2m2HwiKm5lRu2D7oM+Wts87px0zP0Hxhxq7wO81FFbJen2DcUQbkuy9AW5BcrB4rA50vWhEdcjFPNWfsmXT9iwxO2gURv3+8emtKo8CdW34+OJQKmhpSJpza3BW86nFMauVCrqn8cI2D4lrhjms0MxHDmd14TgF+jT1mrQfSoA=
