language: bash
services:
- docker
before_install:
- docker build -t m0rf30/arch-arm-crosscompile .
env:
  global:
  - secure: l0Irjm6sqbkBqX5BGpoP3XhZLzCOiPYnJzz1jVMxSESZ8oEEby28AwqF5OmBJFgpuQOsAkPrA+7wsTRKsonlKIIg4Kma82dDrU3Xam6M/VnoPZAqIpUxYS/HtKR/CUfQL4QDbe+R8hIuW7O0XucO7m3vgFKzJrEZ/qlZZ3NSUfQnmHZrEhU/I7FkSlke+qyKKv/rG4LwzCt1dQr49N14W/Am90Hzax+uA3a648roz08GW09YP5ckZsjDctDKRVPzfwU0MwtldCg4ylajR1Sn2kYPwPhbcj7WNog/uQ29Tia9qZzghSHtrqgL19VwBOaqAcSSaxYHbXxvZRIc7MWiiI5WSOeH3kVCYPJ4GGZ5c6QOMAZMooUf6cuI95njK2K5j4yBn6PvP5Bf1n7DLG1CTrvOASDWy/80hq9OD9OFIVa0Cd8jrG/FmpogIkH+lZetL2PoEwaZa2iGmqsAS1/fIV1L84cCwt4PeYQYiM6wUBCu6Bu8NMXeY9bOqVusSFWwLYXywXL8vrHb1VUahXOpcRsdAOhE6ek2V1cdaZgOF+X8BqH9eum/6MmREJwp5089i1aZceWS1dowiCzmYtz1b1Fa4EScXyZyvSlGi7Dyg842NaSlFVADUdy8x5pzmq1J5R1Gyl5vht178ioPAQ6v9kB801Yb4aMADsR6hJu7qAM=
  - secure: pGG9TIRFDi+VbiJ6/kVV4VTSOLY46YzYwVi8r1vcUuOywcD47ytSyGLGrETNkECVLdt/FbHFN3aMZaT7tUVMFyVlPHLJ4HjlK5KETb6zLmj5qoxTDyC9xizwW8Muf/FLWUp4IP5wWbPoI3xbJOPSOsBJC8tUolheM5pmUoVZxlFQbOa47NbV5hBScCBp5l735y9j8juuFwDWn1gQfCFWXkqtwQgn5tg4ZkK7Cy5ApI1UJBFBLIwTwsRkCkz8gh0QOmeZTUnNYpd2/EHoUni0RjUkb81wlaiVXVqRY71wdlyDD/QJVOJwU/4W5iK0QEVcFQPBD/4rnX+TQ8W7EP62ZmZ51uZSTkLofiUC+DrFacCwXPukb5jdFMwNKEb6MXKmcss/J68dxOd0N4yzmIisYpFJWgSubwaMEEMf3fh2oNaidGvxT/pZRCSQDB0pwqBj9JSkmfuGqcGeNl5vQizrm70dLb1U0reUV6Nb4cN3kZZBqqQiABoLdYDDqXgDAAH9Yu4ey9EKnz1tmF44hN7o8C4oQWpUk+ssKKSFK1q+0/+36xC5lHkW4DUWbEUHPMv6OVvCxl8jyj9fyzEHlPW4/0ZU/f8g4r49YCLXXjSqfmSF43djeRpVaPzeNXuVR0QwuUjK6b1ZkNRvZeAm65JVS0C3wyqBrMFqBvtCFNXQjYA=
deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master
